INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (1, '+13345085334', '1st Baptist Ch. Sandy Springs', '650 Mt Vernon Hwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (2, null, '1st Baptist Church Of Roswell', '710 Mimosa Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (3, null, '2nd Ponce De Leon Bapt Church', '2715 Peachtree Rd Ne - Fam Life Center', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (4, null, 'Abbotts Hill Elementary School', '5575 Abbotts Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (5, null, 'Abernathy Arts Center', '254 Johnson Ferry Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (6, null, 'Adams Park Library', '2231 Campbellton Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (7, null, 'Adams Park Recreation Center', '1620 Delowe Drive SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (8, null, 'Allen Temple AME Church', '1625 Joseph E. Boone Blvd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (9, null, 'Alpharetta Crabapple Government Center', '12624 Broadwell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (10, null, 'Alpharetta Elem School', '192 Mayfield Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (11, null, 'Alpharetta High School', '3595 Webb Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (12, null, 'Alpharetta Library', '10 Park Plaza', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (13, null, 'American Legion Alpharetta', '201 Wills Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (14, null, 'Antioch Baptist Ch Family Cntr', '540 Cameron M Alexander Blvd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (15, null, 'Arthur Langford Junior Recreation Center', '1614 Arthur Langford Jr Pl SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (16, null, 'Asa G. Hilliard Elementary School', '3353 Mount Olive Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (17, null, 'Atlanta History Center', '130 West Faces Ferry Rd NW ', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (18, null, 'Autry Mill Middle School', '4110 Old Alabama Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (19, null, 'Aviation Community Cultural Center', '3900 Aviation Cir Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (20, null, 'Banneker High School', '6015 Feldwood Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (21, null, 'Barnwell Elementary School', '9425 Barnwell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (22, null, 'Bear Creek Middle School', '7415 Herndon Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (23, null, 'Beecher Hills Elementary School', '2257 Bollingbrook Dr SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (24, null, 'Believers Bible Christian Church', '3689 Campbellton Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (25, null, 'Benteen Elem School', '200 Cassanova St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (26, null, 'Berean Seventh Day Advent. Church', '291 Hamilton E Holmes Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (27, null, 'Bethune Elementary School', '5925 Old Carriage Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (28, null, 'Bible Way Ministries', '894 Constitution Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (29, null, 'Birmingham Falls Elem', '14865 Birmingham Hwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (30, null, 'Bolton Academy ', '2268 Adams Dr NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (31, null, 'Bowden Senior Center', '2885 Church St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (32, null, 'Brandon, Morris School', '2741 Howell Mill Rd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (33, null, 'Briar Vista Elementary School', '1131 Briar Vista Ter', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (34, null, 'Brookview Elememtary Sch', '3250 Hammarskjold Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (35, null, 'Buckhead Library', '269 Buckhead Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (36, null, 'Buckhead Theatre    ', '3110 Roswell Rd NE  ', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (37, null, 'Burdett Park Gym', '2945 Burdett Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (38, null, 'Butler Street Baptist Church', '315 Ralph Mcgill Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (39, null, 'C. A. Scott Recreation Bldg', '1565 M L King Jr Dr Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (40, null, 'C.T. Martin Natatorium & Recreation Center', '3201 M L King Jr Dr SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (41, null, 'Cambridge High School', '2845 Bethany Bend', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (42, null, 'Camp Creek Middle School', '4345 Welcome All Ter', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (43, null, 'Camp Truitt Senior Center', '4320 Herschel Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (44, null, 'Cascade Elementary School', '2326 Venetian Dr Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (45, null, 'Cathedral Of Saint Philip', '2744 Peachtree Rd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (46, null, 'Centennial High School', '9310 Scott Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (47, null, 'Center for Civil and Human Rights', '100 Ivan Allen Jr. Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (48, null, 'Central Park Recreation Center', '400 Merritts Ave NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (49, null, 'Central United Methodist Ch', '501 Mitchell St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (50, null, 'Chastain Park Gymnasium', '140 W Wieuca Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (51, null, 'Chattahoochee Hills City Hall', '6505 Rico Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (52, null, 'Christian City - Sparks Auditorium', '7290 Lester Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (53, null, 'Christian City Welcome Center', '7345 Red Oak Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (54, null, 'Church Of The Redeemer', '5185 Peachtree Dunwoody Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (55, null, 'Clear Springs Baptist Church', '11575 Jones Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (56, null, 'Cleveland Avenue Library', '47 Cleveland Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (57, null, 'Cleveland Avenue School', '2672 Old Hapeville Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (58, null, 'Cliftondale Church', '4095 Stonewall Tell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (59, null, 'Cliftondale Community House', '4645 Butner Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (60, null, 'Cliftondale Elementary School', '3340 West Stubbs Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (61, null, 'Coan Park Recreation Center', '1530 Woodbine Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (62, null, 'Cogburn Woods Elem School', '13080 Cogburn Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (63, null, 'College Park Auditorium', '3631 Main Street', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (64, null, 'College Park library', '3647 Main Street', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (65, null, 'Collier Park Recreation Center', '3691 Collier Dr NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (66, null, 'Concord Baptist Church', '3270 Boulder Park Dr SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (67, null, 'Continental Colony Elementary School', '3181 Hogan Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (68, null, 'Coretta Scott King Young Women''s Academy', '1190 Northwest Dr NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (69, null, 'Covenant Presbyterian Church', '2461  Peachtree Road ', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (70, null, 'Crabapple Middle School', '10700 Crabapple Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (71, null, 'Creek View Elementary School', '3995 Webb Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (72, null, 'Creekside High School    ', '7405 Herndon Road ', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (73, null, 'Creel Park', '2775 Creel Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (74, null, 'Crosspointe Community Church', '77 E Crossville Rd Suite 203', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (75, null, 'Dad''s Garage Theatre', '569 Ezzard St SE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (76, null, 'David T. Howard Middle School ', '551 John Wesley Dobbs Ave NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (77, null, 'Deerwood Elementary School', '3070 Fairburn Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (78, null, 'Dobbs Elementary School', '2025 Jonesboro Rd Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (79, null, 'Dogwood Senior Center', '1953 Donald L. Hollowell Pkwy Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (80, null, 'Dolvin Elementary School', '10495 Jones Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (81, null, 'Dr. Robert E. Fulton Reg Library', '5090 Abbotts Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (82, null, 'Dunbar Neighborhood Center', '477 Windsor St SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (83, null, 'East Point First Mallalieu UMC', '2651 Church St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (84, null, 'East Roswell Library', '2301 Holcomb Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (85, null, 'Elkins Pointe Middle School', '11290 Elkins Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (86, null, 'Epworth United Methodist Church', '1561 Mclendon Ave Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (87, null, 'Etris Community Center', '5285 Lakeside Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (88, null, 'FanPlex', '768 Hank Aaron Dr SE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (89, null, 'FanPlex', '768 Hank Aaron Dr SE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (90, null, 'Feldwood Elem School', '5790 Feldwood Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (91, null, 'Fickett School', '3935 Rux Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (92, null, 'Findley Oaks Elementary School', '5880 Findley Chase Drive', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (93, null, 'Fire Station No. 17', '8675 Ridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (94, null, 'First Baptist Church of Fairburn', '23 Malone St SE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (95, null, 'First Iconium Baptist Church', '542 Moreland Ave Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (96, null, 'First Presbyterian Church', '1328 Peachtree Street', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (97, null, 'Flipper Temple AME Church', '580 Atlanta Student Movement Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (98, null, 'Fowling Warehouse', '1356 English St NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (99, null, 'Friendship Baptist Church', '80 Walnut St SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (100, null, 'Friendship Community Church', '4141 Old Fairburn Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (101, null, 'Garden Hills Elementary School', '285 Sheridan Dr NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (102, null, 'Georgia State University - 2nd Floor', '3775 Brookside Pkwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (103, null, 'Georgia Tech McCamish Pavilion', '965 Fowler St NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (104, null, 'Gladys S Dennard Library at South Fulton   ', '4055 Flat Shoals Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (105, null, 'Grant Park Recreation Center', '537  Park Avenue', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (106, null, 'Grant, Bitsy Tennis Center', '2125 Northside Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (107, null, 'Greater Bethany Baptist Church', '786 Thurmond Street', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (108, null, 'Grove Park Recreation Center', '750 Francis Pl Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (109, null, 'Hammond Park Gym', '705 Hammond Drive Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (110, null, 'Harvest Rain Church', '8567 Bohannon Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (111, null, 'Haygood Memorial United Methodist Church ', '1015 E Rock Springs Rd NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (112, null, 'Haynes Bridge Middle School', '10665 Haynes Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (113, null, 'Heard Ferry Elementary School', '6151 Powers Ferry Rd NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (114, null, 'Helene S. Mills Senior Center', '515 John Wesley Dobbs Ave NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (115, null, 'Hembree Springs Elementary School', '815 Hembree Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (116, null, 'Heritage Hall Sandy Spring', '6110 Blue Stone Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (117, null, 'Highpoint Elementary School', '520 Greenland Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (118, null, 'Hillside Elem School', '9250 Scott Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (119, null, 'Historic Academy of Medicine   ', '875 West Peachtree St NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (120, null, 'Hopewell Baptist Church', '15730 Hopewell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (121, null, 'Hopewell Middle School', '13060 Cogburn Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (122, null, 'Hoyt Smith Center', '3444 N Fulton Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (123, null, 'Hugh Otis Burgess Elementary School', '480 Clifton St Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (124, null, 'Impact Church', '2323 Sylvan Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (125, null, 'Independence High School', '791 Mimosa Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (126, null, 'Ison Springs Elementary School      ', '8261 Ison Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (127, null, 'Israel Baptist Church', '2071 Hosea L Williams, Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (128, null, 'Jackson Memorial Baptist Church', '534 Fairburn Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (129, null, 'Jackson, Esther S Elem School', '1400 Martin Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (130, null, 'Jackson, Warren T School', '1325 Mt Paran Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (131, null, 'James Orange Park', '1305 Oakland Ln', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (132, null, 'Jefferson Recreation Center', '1431 Norman Berry Drive', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (133, null, 'John Birdine Neighborhood Facility', '215 Lakewood Way Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (134, null, 'Johns Creek Environmental Campus', '8100 Holcomb Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (135, null, 'Johns Creek High School', '5575 State Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (136, null, 'Johns Crk United Methodist Ch', '11180 Medlock Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (137, null, 'Lake Forest Elementary School', '5920 Sandy Springs Cir', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (138, null, 'Lang-Carson Recreation Center', '100 Flat Shoals Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (139, null, 'Langston Hughes High School', '7510 Hall Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (140, null, 'Lebanon Church', '11250 Crabapple Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (141, null, 'Liberty Baptist Church', '395 Chamberlain St Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (142, null, 'Life Center Ministries Inc.', '2690 Mount Vernon Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (143, null, 'Lindsay Street Baptist Church', '550 Lindsay St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (144, null, 'Little 5 Points Comm Center', '1083 Austin Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (145, null, 'Location', 'Address', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (146, null, 'Louise Watley Library at Southeast Atlanta', '1463 Pryor Road Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (147, null, 'Lutheran Church of the Redeemer', '731 Peachtree St NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (148, null, 'M28 Church', '1150 Niles Avenue', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (149, null, 'Manning Oaks Elementary School', '405 Cumming St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (150, null, 'Mary Lin Elementary School', '586 Candler Park Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (151, null, 'Mcghee, Joseph Tennis Center', '820 Beecher Ct', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (152, null, 'McNair Middle School', '2800 Burdett Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (153, null, 'Messiah Lutheran Church', '4765 Kimball Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (154, null, 'Metropolitan Library', '1332 Metropolitan Pkwy Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (155, null, 'Milton Library', '855 Mayfield Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (156, null, 'Mimosa Elementary School', '1550 Warsaw Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (157, null, 'Morehouse College-Archer Hall', '876 Atlanta Student Movement Blvd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (158, null, 'Morningside Baptist Church Gym', '1700 Piedmont Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (159, null, 'Morningside Elementary School', '774 Virginia Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (160, null, 'Morningside Prebyterian Church ', '1411 North Moringside Dr NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (161, null, 'Morris Brandon Primary Ctr. School', '2845 Margaret Mitchell Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (162, null, 'Mount Carmel Baptist Church', '2755 Campbellton Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (163, null, 'Mount Ephraim Baptist Church', '1202 West Marietta St NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (164, null, 'Mount Pisgah United Methodist Church', '2850 Old Alabama Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (165, null, 'Mountain Park Community Center', '100 Lakeshore Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (166, null, 'Mt Vernon Baptist Church', '850 Mt Vernon Hwy Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (167, null, 'New Beginnings Senior Center   ', '66 Brooks Drive', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (168, null, 'New Life Presbyterian Church', '6600 Old National Hwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (169, null, 'New Prospect Elementary', '3055 Kimball Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (170, null, 'Nolan, Love T. Elementary Sch', '2725 Creel Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (171, null, 'North Annex', '7741 Roswell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (172, null, 'North Fulton Training Center    ', '5025 Roswell Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (173, null, 'North River Baptist Church', '12090 Hardscrabble Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (174, null, 'North Springs High School', '7447 Roswell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (175, null, 'Northeast/Spruill Oaks Library', '9560 Spruill Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (176, null, 'Northside Library', '3295 Northside Pkwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (177, null, 'Northview High School', '10625 Parsons Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (178, null, 'Northwest Library at Scotts Crossing', '2489 Perry Blvd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (179, null, 'Northwood Elementary School', '10200 Wooten Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (180, null, 'Oakley Elementary School', '7220 Oakley Terrace', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (181, null, 'Ocee Elem School', '4375 Kimball Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (182, null, 'Old Adamsville Emergency Shelter ', '3404 Delmar Lane', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (183, null, 'Open Word Christian Ministries', '6230 Highway 92', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (184, null, 'Ormewood Park Presby. Church', '1071 Delaware Avenue', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (185, null, 'Palmetto Library', '9111 Cascade Palmetto Hwy', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (186, null, 'Park Tavern', '500 10th St NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (187, null, 'Parkside Elem School', '685 Mercer St Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (188, null, 'Paul L. Dunbar School', '500 Whitehall Terrace Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (189, null, 'Peachtree Christian Church', '1580 Peachtree Street Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (190, null, 'Peachtree Hills Recreation', '308 Peachtree Hills Ave Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (191, null, 'Perkerson Park Rec Center', '770 Deckner Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (192, null, 'Piedmont Park Magnolia Hall', '1320 Monroe Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (193, null, 'Pittman Park Rec Center', '950 Garibaldi St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (194, null, 'Ponce City Market ', '675 Ponce De Leon Ave NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (195, null, 'Ponce De Leon Library', '980 Ponce De Leon Ave', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (196, null, 'Prince Of Peace Lutheran Church', '10250 Haynes Bridge Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (197, null, 'Ptree Presbyterian Church', '3434 Roswell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (198, null, 'Radcliffe Presbyterian Church', '286 Hamilton E. Holmes Dr NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (199, null, 'Ralph Bunche Middle School', '1925 Niskey Lake Rd Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (200, null, 'Ridgeview Middle School', '5340 South Trimble Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (201, null, 'River Eves Elementary', '9000 Eves Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (202, null, 'River Trial Middle School ', '10795 Rogers Circle', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (203, null, 'Rivers, E School', '8 Peachtree Battle Ave NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (204, null, 'Rosel Fann Recreation Center', '365 Cleveland Ave SE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (205, null, 'Roswell High School', '11595 King Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (206, null, 'Roswell Library', '115 Norcross St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (207, null, 'Roswell North Elementary School', '10525 Woodstock Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (208, null, 'S L Lewis Elementary School', '6201 Connell Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (209, null, 'Saint Luke''s Episcopal Church', '435 Peachtree St NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (210, null, 'Saint Mary''s Orthodox Church', '1950 Old Alabama Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (211, null, 'Saint Philips Ame Church', '240 Candler Rd Se', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (212, null, 'Saint.Mark AME Church', '3605 Campbellton Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (213, null, 'Salem Baptist Church', '2283 Baker Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (214, null, 'Sandtown Park Recreation Center', '5320 Campbellton Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (215, null, 'Sandy Springs Library', '395 Mount Vernon Hwy Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (216, null, 'Sandy Springs Middle School', '8750 Pride Place', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (217, null, 'Sandy Springs United Meth. Ch.', '86 Mount Vernon Hwy Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (218, null, 'Sarah Rawson Smith Elem School', '370 Old Ivy Rd Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (219, null, 'Sarah Smith Intermediate School', '4141 Wieuca Rd NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (220, null, 'Scott Elem School', '1752 Hollywood Rd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (221, null, 'Shakerag Elementary School', '10885 Rogers Circle', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (222, null, 'Sherwood Events         ', '8610 Roswell Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (223, null, 'Simpson Street Church Of Christ', '800 Joseph E. Boone Blvd Nw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (224, null, 'Solid Rock Pentecostal Church', '4707 Washington Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (225, null, 'South Atlanta High School', '800 Hutchens Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (226, null, 'Southwest Art Center', '915 New Hope Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (227, null, 'Southwest Atlanta Christian Academy ', '3911 Campbellton Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (228, null, 'Southwest Regional Library', '3665 Cascade Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (229, null, 'Spalding Drive Elem School', '130 West Spalding Drive Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (230, null, 'Springfield Baptist Church', '1730 Hollywood Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (231, null, 'St James Methodist Ch', '4400 Peachtree Dunwoody Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (232, null, 'St Jude Catholic Church', '7171 Glenridge Dr Ne', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (233, null, 'St Paul''s Episcopal Church', '306 Peyton Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (234, null, 'St Peters Bapt Church Rec Bldg', '1558 Venetian Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (235, null, 'St. James Um Church', '3000 Webb Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (236, null, 'St. Stephens Miss. Baptist Church', '2670 Hogan Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (237, null, 'Summit Hill Elementaty School', '13855 Providence Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (238, null, 'Sutton Middle School', '2875 Northside Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (239, null, 'Sweet Apple Elementary School', '12025 Etris Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (240, null, 'Sylvan Middle School     ', '1461 Sylvan Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (241, null, 'Taylor Road Middle School', '5150 Taylor Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (242, null, 'Temple Emanuel', '1580 Spalding Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (243, null, 'The Enon Church', '3550 Enon Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (244, null, 'The Fox Theatre  ', '660 Peachtree St NE', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (245, null, 'The Gathering Place   ', '6280 Bryant St    ', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (246, null, 'The Kindezi School - West', '286 Wilson Mill Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (247, null, 'The Love Center GRSBC', '1680 Campbellton Rd SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (248, null, 'Therrell, D.M. High School', '3099 Panther Trail Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (249, null, 'Thomasville Recreation Center', '1835 Henry Thomas Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (250, null, 'Tracey Wyatt Recreation Center', '2300 Godby Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (251, null, 'Trinity Presbyterian Church', '3003 Howell Mill Road NW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (252, null, 'Tuskegee Airmen Academy', '1626 Westhaven Dr SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (253, null, 'Vickery Mill Elementary School', '1201 Alpharetta St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (254, null, 'W Oakland Missionary Bapt Ch', '1025 Violet St', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (255, null, 'Washington Park Library', '1116 M L King Jr Dr Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (256, null, 'Webb Bridge Middle School', '4455 Webb Bridge Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (257, null, 'Welcome All Park, Community House', '4255 Will Lee Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (258, null, 'West End Library', '525 Peeples Street SW', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (259, null, 'West Hunter Street Baptist Church', '1040 Ralph David Abernathy Blvd Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (260, null, 'West Manor Park', '3240 West Manor Cir', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (261, null, 'Westlake High School', '2400 Union Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (262, null, 'Westside Community Church', '2114 Martin Luther King Jr Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (263, null, 'William Walker Recreation Center', '2405 Fairburn Rd Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (264, null, 'Wills Recreation Center', '11925 Wills Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (265, null, 'Wilson Creek Elementary Sch', '6115 Wilson Rd', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (266, null, 'Wolf Creek Library', '3100 Enon Rd Sw', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (267, null, 'Woodland Elem. School', '1130 Spalding Dr', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (268, null, 'Woodland Middle School', '2745 Stone Road', null, 1);
INSERT INTO sse.polling_places (id, phone, name, address, precincts, status) VALUES (269, null, 'World Harvest Church       ', '320 Hardscrabble Rd', null, 1);